from models.scan_state import ScanState

class ReportService:
    def generate_report(self, state: ScanState) -> str:
        report = f"# SYNOD Bug Bounty Report\n\n"
        report += f"## Summary\nTarget: {state.target}\nStatus: {state.status}\n\n"
        report += f"## Recon Findings\n```json\n{state.recon_data}\n```\n\n"
        report += f"## Potential Vulnerabilities\n"
        for vuln in state.vulnerabilities:
            report += f"- {vuln.get('title', 'Unknown')}: {vuln.get('description', '')}\n"
        report += f"\n## Recommended Fixes\n(To be generated by AI)\n"
        return report

report_service = ReportService()
